halmd slit_simulation_NVE.lua -v \
    --input /group/ag_compstatphys/data/tolga/walls/crystalline_walls_W15_rho0.8.h5 \
    --output /group/ag_compstatphys/data/tolga/simulation/slit_05s_NVE_amorphous_05lc_testing \
    --pore_width 15 \
    --fluid_density 0.7 \
    --cutoff 1.0 \
    --temperature 1.0 \
    --equilibrium_time 100 \
    --production_time 100 \
    --slab width 0.5 \
    --slab axis "z" 